/// Flutter icons Peppex
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Peppex
///      fonts:
///       - asset: fonts/Peppex.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Peppex {
  Peppex._();

  static const _kFontFam = 'Peppex';
  static const _kFontPkg = null;

  static const IconData dashicons_hidden_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashicons_visibility = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eva_search_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_twotone_menu_book = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whh_foodtray = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ant_design_shopping_cart_outlined = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_lock_fill = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bytesize_filter = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bytesize_user = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carbon_email = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
